//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralInsurancePrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimInfo
    {
        public int Claim_No { get; set; }
        public Nullable<System.DateTime> Claim_Date { get; set; }
        public string Approval_Result { get; set; }
        public Nullable<float> Claim_Amount_Approved { get; set; }
        public string Claim_Reason { get; set; }
        public Nullable<int> Policy_no { get; set; }
        public Nullable<int> Vehicle_id { get; set; }
        public Nullable<int> Regist_Id { get; set; }
    
        public virtual PolicyInfoTB PolicyInfoTB { get; set; }
        public virtual RegistrationInfo RegistrationInfo { get; set; }
        public virtual VehicleInsuranceInfo VehicleInsuranceInfo { get; set; }
    }
}
