//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralInsurancePrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationInfo()
        {
            this.ClaimInfoes = new HashSet<ClaimInfo>();
            this.InsurancePlanInfoes = new HashSet<InsurancePlanInfo>();
            this.VehicleInsuranceInfoes = new HashSet<VehicleInsuranceInfo>();
        }
    
        public int Reg_Id { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<float> PhoneNumber { get; set; }
        public string CustomerAddress { get; set; }
        public string Paassword { get; set; }
        public string ConfirmPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimInfo> ClaimInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePlanInfo> InsurancePlanInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInsuranceInfo> VehicleInsuranceInfoes { get; set; }
    }
}
